# TODO Warning: If we change the pipeline it resets the github.run_number so the deployment will break
# if it overlaps with an existing deployment number
name: Angular CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci-cd:
    if: github.ref == 'refs/heads/master' && github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/deploy.yml
    with:
      acm-certificate-arn: UPDATE_THIS_PARAMETER
      angular-release-build-folder-name: UPDATE_THIS_PARAMETER
      aws-region: UPDATE_THIS_PARAMETER
      cloudfront-distribution: UPDATE_THIS_PARAMETER
      cloudfront-folder-name: UPDATE_THIS_PARAMETER
      environment-name: UPDATE_THIS_PARAMETER
      route53-dns-record-name: UPDATE_THIS_PARAMETER
      route53-hosted-zone-id: UPDATE_THIS_PARAMETER
      s3-bucket-name: UPDATE_THIS_PARAMETER
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
