AWSTemplateFormatVersion: "2010-09-09"
Description: "This stack has all for cloudfront."
Resources:

  ApiRoute53Record:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      AliasTarget:
        DNSName: !GetAtt ApiCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      Name: !Ref ApiHost
      Type: A
      HostedZoneId: !Ref HostedZoneId
    DependsOn:
      - ApiCloudFrontDistribution

  ApiCloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref ApiHost
        DefaultCacheBehavior:
          AllowedMethods: ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"]
          Compress: true
          ForwardedValues:
            QueryString: true
            Headers:
              - Authorization
              - Accept
          TargetOriginId: "ApiGateway"
          ViewerProtocolPolicy: "redirect-to-https"
        Enabled: true
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
            DomainName: !Join
              - ""
              - - Fn::ImportValue:
                    !Sub "${ApiGatewayStack}:rest-api:id"
                - ".execute-api."
                - !Ref 'AWS::Region'
                - ".amazonaws.com"
            Id: "ApiGateway"
            OriginPath: !Join
              - ""
              - - '/'
                - Fn::ImportValue:
                    !Sub "${ApiGatewayStack}:api-gateway-stage:id"
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only

Parameters:
  ApiHost:
    Type: String
  CertificateArn:
    Type: String
  ApiGatewayStack:
    Type: String
  HostedZoneId:
    Type: String

Outputs:
  ApiCloudFrontDistribution:
    Description: The reference to the api cloudfront distribution
    Value: !Ref ApiCloudFrontDistribution
    Export:
      Name: !Sub "${AWS::StackName}:api-cloudfront-distribution:id"
  ApiCloudFrontDistributionDomainName:
    Description: The reference to the domain name of the cloudfront distribution
    Value: !GetAtt ApiCloudFrontDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}:api-cloudfront-distribution:domain-name"
